version: '3'
services:

 API1:
    image: service1api
    build:
      context: ./src/service1.api
      dockerfile: Dockerfile
    ports:
      - "9000:80"
        
 API2:
    image: service2api
    build:
      context: ./src/service2.api
      dockerfile: Dockerfile
    ports:
      - "9001:80"